service: ironode
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-2
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  hell:
    handler: handler.hell
    events:
      - http:
          path: hell
          method: get
  home:
    handler: handler.home
    events:
      - http:
          path: home
          method: get